In [2]:
import numpy as np

np.array?

np.array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [4]:
# NumPy array vs Python list performance

import time 
import numpy as np

size_of_vec = 1000000

def python_list():
    ti = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i]+ y[i] for i in range(len(x))]
    return time.time() - ti

def numpy_array():
    t1 = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x + y
    return time.time() - t1

count1 = python_list()
count2 = numpy_array()
print("**** Test run with {} elements ****". format(size_of_vec))
print("Python list: {}". format(count1))
print("Numpy array: {}". format(count2))
print("Numpy array is " +str(count1/count2) + "faster!")

**** Test run with 1000000 elements ****
Python list: 0.17644238471984863
Numpy array: 0.005009651184082031
Numpy array is 35.22049305158957faster!


In [5]:
# 資料類型確認
arr = np.array([3, 5, 7, 9])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# 如果希望宣告變數後，直接預覽變數，可以用「;」隔開，寫在同一行:
a = np.array([3, 5, 7, 9]); a

array([3, 5, 7, 9])

In [8]:
# np.arange(): 從數值範圍來建立陣列
# 跟 range() 用法一樣
'''
用法：
numpy.array([start, ]stop, [stop, ]dtype=None, *, like=None)
'''
a = np.arange(10);a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 取得陣列 [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.arange(1, 10); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 1 ~ 10 之間，每隔 3 個元素，加入資料到陣列: [1, 4, 7]
a = np.arange(1, 10, 3); a

array([1, 4, 7])

In [15]:
# 線性分割 np.linspace(): 從數值範圍透過線性切割建立陣列
'''
用法：
args - start elment, end elment, number of elments
'''
a = np.linspace(0, 10, 4); a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
# Numpy 資料型態
# 自動判斷資料型態
a = np. array([1, 2, 3 ,4]); a.dtype

dtype('int64')

In [17]:
# 自動判斷資料型態 (其中一個元素變成浮點數，dtype 會自動轉型)
a = np.array([1.3, 2, 3, 4]); a.dtype

dtype('float64')

In [21]:
# 指定陣列每一個資料的資料型態 (指定 float 預設為 float64)
a = np.array([1, 2, 3, 4], dtype="float"); a.dtype
# arr8.dtype

dtype('float64')

In [23]:
# Unicode 最多9個字
arr = np.array(["GoodBye", "Welcome", "Tata", "Goodnight"]); arr.dtype

dtype('<U9')

In [24]:
# 最多9個字元
arr[2]= "this is a book"
arr[2]

np.str_('this is a')

In [25]:
# numpy 有boolean資料型態 適用於masking

a = np.array([True, False, True, False]); a.dtype

dtype('bool')

In [26]:
# 傳回一個全新的整數陣列
a_float = np.array([1, 2, 3, 4], dtype="float"); a_float.dtype

a_int = a_float.astype(int); a_int.dtype

print("a_float: ", a_float)
print(f"a_float 記憶體位址:{id(a_float)}")

print("a_int: ", a_int)
print(f"a_int 記憶體位址: {id(a_int)}")

a_float:  [1. 2. 3. 4.]
a_float 記憶體位址:2274570794736
a_int:  [1 2 3 4]
a_int 記憶體位址: 2274575849616


## Numpy 陣列的屬性
- shape, ndim, dtype, itemsize, size

Dimensions or Axes in Numpy
- Scalars(0D Arrays)
- Vectors(1D Arrays)
- Matrices(2D Arrays)
- Tensor(3D Arrays)

In [28]:
# Scalars (0D arrays)
s = np.array(21)

print(s)
print("Numberof axes:", s.ndim)
print("data type:", s.dtype)
print("data size:", s.size)
print("Shape:", s.shape)

21
Numberof axes: 0
data type: int64
data size: 1
Shape: ()


In [29]:
# Vectors (1D Arrays) 向量 (一維陣列)
vec = np.array([-1, 2, 7, 9, 2])

print(vec)
print("Numberof axes:", vec.ndim)
print("data type:", vec.dtype)
print("data size:", vec.size)
print("Shape:", vec.shape)

[-1  2  7  9  2]
Numberof axes: 1
data type: int64
data size: 5
Shape: (5,)


In [30]:
# Matrices (2D Arrays) 矩陣 (二維陣列)
mat = np.array([
    [1.2, 2.3, 3.3],
    [5.5, 6.3, 7.5]
])

print(mat)
print("Numberof axes:", mat.ndim)
print("data type:", mat.dtype)
print("data size:", mat.size)
print("Shape:", mat.shape)


[[1.2 2.3 3.3]
 [5.5 6.3 7.5]]
Numberof axes: 2
data type: float64
data size: 6
Shape: (2, 3)


In [32]:
# 3D Arrays 3D陣列
t = np.array([
    [[1, 3, 9],
     [7, -6, 2]],

     [[2, 3, 5],
      [0, -2, -2]],

      [[9, 6, 2],
       [-7, -3, -12]],

       [[2, 4, 5],
        [-1, 9, 8]]
])

print(t)
print("Numberof axes:", t.ndim)
print("data type:", t.dtype)
print("data size:", t.size)
print("Shape:", t.shape)


[[[  1   3   9]
  [  7  -6   2]]

 [[  2   3   5]
  [  0  -2  -2]]

 [[  9   6   2]
  [ -7  -3 -12]]

 [[  2   4   5]
  [ -1   9   8]]]
Numberof axes: 3
data type: int64
data size: 24
Shape: (4, 2, 3)


## Numpy 陣列創建函式

These function include
- numpy.zeros,
- numpy.ones,
- numpy.eye,
- numpy.rand,
- numpy.random.randn,
- numpy.empty

In [33]:
# numpy.zeros
#Produce 4x2 array of zeros.
#配置記憶體空間，並將記憶體清0

arr_zeros = np.zeros((4,2)); arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
# numpy.ones
# Produces 2x3x2 array of 1's.
# pandas 只支援二維資料結構
# 在深度學習tensor資料型態才會是三維資料結構
arr_ones = np.ones((2, 3, 4)); arr_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
# numpy.eye
# Produces identity matrix
arr_eye = np.eye(3); arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# numpy.empty(): 建立尚未初始化的陣列，裡面的元素是隨機產生的結果，換句話說，只產生陣列，值都是隨機產生的
# 註：若需要初始化(同時給元素預設的值)，建議使用 np.zeros、np.ones 或 np.fill
'''
numpy.empty(shape, dtype=float, order="C", *, like=None)
'''
arr_empty = np.empty((3, 3)); arr_empty

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# numpy.full(): 建立填滿 fill_value 得陣列，透過 shape 指定幾維
'''
numpy.full(shape, full_value, dtype=None, order="c", *, like=None)
'''
arr_full = np.full((3,4), 10); arr_full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [41]:
# numpy.random.rand

# Using the rand,randn function
# rand(m) produces an array of the given shape
# with uniformly distributed random numbers over (0,1)
np.random.seed(50) # set seed 隨機產生的值才會固定
arr_random = np.random.rand(10); arr_random

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ,
       0.99657423, 0.4081972 , 0.77189399, 0.76053669, 0.31000935])

In [44]:
# randn(m) produces m normally distributed (Gaussian) random numbers
arr_random_num = np.random.randn(3); arr_random_num

array([-0.99752606,  1.59890829,  3.31407535])