In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.0'

## 隨機函數
- np.random.rand(dim0\[, dim1, dim2, ...\])
- np.random.randint(low, high=None, size=None)
- 參考資料: 
  - [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
  - [python numpy 常用随机数的产生方法](https://blog.csdn.net/m0_37804518/article/details/78490709)

In [3]:
'''
np.random.seed(42)
numpy.random.rand(): 設定種子後，取得隨機亂數

註: np.random.seed() 的引數固定，隨機產生的值也會固定，亂數的值介於 [0, 1)
'''
np.random.seed(30)
a= np.random.rand(3);a

array([0.64414354, 0.38074849, 0.66304791])

In [7]:
'''
np.random.randint(start, end - 1, size=數量): 產生 start 到 end - 1 之間的整數值

隨機產生 100 位同學的成績
'''
a = np.random.randint(0, 100, size= (1, 100), dtype="int32"); a

# np.array((2,4))

array([[29, 30, 83, 95, 16, 71, 86, 71, 91, 42,  2, 78, 57, 83, 68,  1,
        47, 64, 40, 56, 20, 40,  2, 71, 77, 94, 11, 44, 50, 71, 66,  9,
        20, 28, 65, 37, 80, 72, 93, 68, 61, 57, 81, 19, 42, 64, 16, 65,
        63,  8, 15, 83, 81, 20, 91, 94, 96, 24, 23, 25,  6, 97, 83, 18,
        93, 17, 32,  6, 80, 91, 59, 12, 14, 51,  2, 61, 59, 82, 21,  1,
        75, 47, 18, 51, 79, 68, 53, 63,  8, 12, 82, 15, 81, 20, 64, 57,
        58, 30, 42, 63]], dtype=int32)

In [11]:
'''
np.random.shuffle(): 陣列元素重新排列
'''
x = np.arange(10)
np.random.shuffle(x)
x


array([2, 5, 9, 4, 3, 6, 0, 7, 8, 1])

## 統計運算

### 平均 mean()

In [12]:
# mean(): 元素平均值 -1D
x = np.array([1, 2, 3, 4])
np.mean(x)

np.float64(2.5)

In [13]:
# mean(): 元素平均值 - 2D
x = np.array([[1, 2],[3, 4]])
np.mean(x)

np.float64(2.5)

In [14]:
# mean() 加上 axis
x = np.array([[1, 2],[3, 4]])
np.mean(x, axis= 0)

array([2., 3.])

### 中位數 median()

In [15]:
# median():中位數
x = np.array([[12, 7, 4],[3, 2, 6]])
np.median(x)
# [2, 3, 4, 6, 7, 12]
# (4+6) / 2

np.float64(5.0)

In [16]:
# median() 加上 axis
np.median(x, axis= 0)

array([7.5, 4.5, 5. ])

### 變異數 var()

In [17]:
# var(): 變異數 (variance) (離散隨機變數) (一維陣列)
'''
import math
mean = (1 + 2 + 3 + 4) / 4
(math.pow(1 - mean, 2) + math.pow(2 - mean, 2) + math.pow(3 - mean, 2) + math.pow(4 - mean, 2)) / 4

補充: var() 也可以設定 axis
'''
x= np.array([1, 2, 3, 4])
np.var(x)

np.float64(1.25)

In [19]:
# var(): 變異數 (variance) (離散隨機變數) (二維陣列)
'''
import math

x_ = x.ravel()
mean_X = np.mean(x_)
sum = 0

for i in x_:
    sum += math.pow(i-mean_X, 2)

sum / len(x_)
'''
x = np.array([[1, 2, 3, 4], 
              [2, 4, 6, 8]])
np.var(x)

np.float64(4.6875)

### 標準差 std()

In [20]:
# std(): 標準差 (standard deviation) - 1D array
'''
變異數 = 「標準差」的平方
標準差 = 「變異數」開根號
'''

x = np.array([1, 2, 3, 4])
np.std(x)

np.float64(1.118033988749895)

In [21]:
# std(): 標準差 (standard deviation) - 2D array
x = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])
np.std(x)

np.float64(2.165063509461097)

In [22]:
# std() 加上 axis
np.std(x, axis= 0)

array([0.5, 1. , 1.5, 2. ])

In [23]:
# std() 加上 axis
np.std(x, axis= 1)

array([1.11803399, 2.23606798])

### 累計加總 cumsum()

In [30]:
# 1D Array
x = np.arange(10)

np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [33]:
# 2D Array
# reshape(2,-1)  
# 將數組重新塑形為 2 行；-1 是一個特殊值，表示自動計算合適的大小。
x = np.arange(10).reshape(2,-1); x

# np.cumsum(x)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
np.cumsum(x, axis= 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]])

In [35]:
np.cumsum(x, axis= 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13]])

## 邏輯運算

### any()

In [40]:
# 一個滿足就返回 True
ar = np.array([9, 9, 4, 7])
np.any((ar % 7) == 0)
#  any((ar % 7) == 0)

np.True_

### all()

In [41]:
# 全部為真才返回 True
ar=np.array([9, 9, 4, 7])
np.all((ar%7)==0)

np.False_

In [42]:
ar=np.array([7, 14, 28, 35])
np.all((ar%7)==0)

np.True_

## 廣播 Broadcasting

執行 2 個陣列運算時，原則上必須外形相同才能運算，如果不同，可以使用廣播 (broadcasting) 機制，將小陣列「擴大」到兩個陣列都相同，之後再進行運算。

![Computation on Arrays: Broadcasting](https://i.imgur.com/CuB6Bsh.png)
參考資料: [Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [43]:
ar = np.ones((3, 2)); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
ar2 = np.array([2,3]); ar2

array([2, 3])

In [45]:
# 缺失維度自動補滿
ar + ar2

array([[3., 4.],
       [3., 4.],
       [3., 4.]])

### Broadcasting works across dimensions

In [46]:
ar = np.array([[23, 24, 25]]); ar

array([[23, 24, 25]])

In [48]:
ar.T

array([[23],
       [24],
       [25]])

In [49]:
ar.T + ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])