In [2]:
import numpy as np

np.array?

np.array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [4]:
# NumPy array vs Python list performance

import time 
import numpy as np

size_of_vec = 1000000

def python_list():
    ti = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i]+ y[i] for i in range(len(x))]
    return time.time() - ti

def numpy_array():
    t1 = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x + y
    return time.time() - t1

count1 = python_list()
count2 = numpy_array()
print("**** Test run with {} elements ****". format(size_of_vec))
print("Python list: {}". format(count1))
print("Numpy array: {}". format(count2))
print("Numpy array is " +str(count1/count2) + "faster!")

**** Test run with 1000000 elements ****
Python list: 0.17644238471984863
Numpy array: 0.005009651184082031
Numpy array is 35.22049305158957faster!


In [5]:
# 資料類型確認
arr = np.array([3, 5, 7, 9])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# 如果希望宣告變數後，直接預覽變數，可以用「;」隔開，寫在同一行:
a = np.array([3, 5, 7, 9]); a

array([3, 5, 7, 9])

In [8]:
# np.arange(): 從數值範圍來建立陣列
# 跟 range() 用法一樣
'''
用法：
numpy.array([start, ]stop, [stop, ]dtype=None, *, like=None)
'''
a = np.arange(10);a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 取得陣列 [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.arange(1, 10); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 1 ~ 10 之間，每隔 3 個元素，加入資料到陣列: [1, 4, 7]
a = np.arange(1, 10, 3); a

array([1, 4, 7])

In [15]:
# 線性分割 np.linspace(): 從數值範圍透過線性切割建立陣列
'''
用法：
args - start elment, end elment, number of elments
'''
a = np.linspace(0, 10, 4); a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
# Numpy 資料型態
# 自動判斷資料型態
a = np. array([1, 2, 3 ,4]); a.dtype

dtype('int64')

In [17]:
# 自動判斷資料型態 (其中一個元素變成浮點數，dtype 會自動轉型)
a = np.array([1.3, 2, 3, 4]); a.dtype

dtype('float64')

In [21]:
# 指定陣列每一個資料的資料型態 (指定 float 預設為 float64)
a = np.array([1, 2, 3, 4], dtype="float"); a.dtype
# arr8.dtype

dtype('float64')

In [23]:
# Unicode 最多9個字
arr = np.array(["GoodBye", "Welcome", "Tata", "Goodnight"]); arr.dtype

dtype('<U9')